### ISSUE TITLE
Update RPC protocol to be less verbose

### ISSUE THREAD

**Issue by mattbasta** [mattbasta/webraft#3]
Old:

``` json
{"id":372,"res":true,"term":1}
{"req":["AppendEntries",-1,-1,[],-1],"id":372,"term":1}
```

New:

``` json
[372,1,"res",true]
[372,1,"req","AppendEntries",-1,-1,[],-1]
```

Array members for calls
1. ID
2. Term
3. Type
4. Method

Subsequent members are params

Array members for responses:
1. ID
2. Term
3. Type
4. Result (optional for void)

**Comment by mattbasta** [comment]
@tarrencev Thoughts?

**Comment by tarrencev** [comment]
I'm not sure, I would prefer objects to arrays. I'd rather do `obj.res` than `arr[1]`.

**Comment by mattbasta** [comment]
This isn't for an API, it's for an over-the-wire protocol

**Comment by tarrencev** [comment]
Oh word, then yeah makes sense
